### ISSUE TITLE
[tech] duplicate `@types/node` with different version

### ISSUE THREAD

**Issue by p4dd9** [phaserjs/discord-multiplayer-template#2]
The root package.json includes a 

```
"devDependencies": {
    "@types/node": "^20.12.7"
  }
```

whereas `package.json` in the server directory includes in devDependencies

```
"@types/node": "^14.14.22",
```

It would be nice to have latest node typings for the project, and both packages share the same node typings.

if the whole project is run within node 20.x.x one could also remove the `cross-fetch` dependency to reduce maintenance and complexity cost.

**Comment by candelibas** [comment]
Thanks updated!
