### ISSUE TITLE
[feauture] Allow local browser testing with DiscordSDK

### ISSUE THREAD

**Issue by p4dd9** [phaserjs/discord-multiplayer-template#3]
As a developer I would expect to run the project in my browser locally without opening an ssl tunnel to test my discord phaser js activity, so that I can also open multiple tabs per game room and test e.g. two player scenarios.

The official discord colyseus template mocks away the discordSDK allowing query params to be used: https://github.com/discord/embedded-app-sdk/blob/main/examples/react-colyseus/packages/client/src/discordSdk.tsx 

It would be nice to add this snippet to get a showcase how discord app embededd sdk functions could be used in phaser, e.g. display "username"  for a player, in local browser development

**Comment by candelibas** [comment]
This was in our list, added now! Thanks a lot!
