### ISSUE TITLE
Template does not run gameplay from main template

### ISSUE THREAD

**Issue by Draice** [phaserjs/discord-multiplayer-template#4]
I'm getting this error in the console:

![image](https://github.com/phaserjs/discord-multiplayer-template/assets/12833616/b94c81fe-cb6c-479c-81d0-24762cad0b5c)

The only change I've made is to the dev command, to get it working on Windows:

`"dev": "nodemon --watch src -e ts,ejs --exec \"%npm_execpath%\" start",`

When I click pass the main menu, I see this screen:

![image](https://github.com/phaserjs/discord-multiplayer-template/assets/12833616/4cc6c618-8d83-48e3-a552-3923f780b5ff)

It doesn't do anything else from that point. I'm running this on Node 21.7.3, and this is the terminal output I see when I run "npm run dev":

```
PS D:\Projects\hero> npm run dev

> hero@1.0.0 dev
> pnpm run --filter "./packages/**" --parallel dev

Scope: 2 of 3 projects
packages/client dev$ vite
packages/server dev$ nodemon --watch src -e ts,ejs --exec "%npm_execpath%" start
packages/server dev: [nodemon] 3.1.0
packages/server dev: [nodemon] to restart at any time, enter `rs`
packages/server dev: [nodemon] watching path(s): src\**\*
packages/server dev: [nodemon] watching extensions: ts,ejs
packages/server dev: [nodemon] starting `C:\Users\danie\AppData\Roaming\npm\node_modules\pnpm\bin\pnpm.cjs start`
packages/client dev:   VITE v5.2.8  ready in 1480 ms
packages/client dev:   ➜  Local:   http://localhost:3000/
packages/client dev:   ➜  Network: use --host to expose

[main 2024-06-16T11:07:25.447Z] update#setState idle
[main 2024-06-16T11:07:55.498Z] update#setState checking for updates
[main 2024-06-16T11:07:56.546Z] update#setState idle

```

**Comment by syslev** [comment]
Same issue here. No changes made to anything other than what is in the tutorial.

**Comment by candelibas** [comment]
Thank you for letting us know. This has been fixed now.
