### ISSUE TITLE
Assets not rendered in Discord activity

### ISSUE THREAD

**Issue by chauvm** [phaserjs/discord-multiplayer-template#5]
Hi!
1. Should this line under `package.json` be
```
    "tunnel": "cloudflared tunnel --url http://localhost:3000"
```
instead of 
```
    "tunnel": "cloudflared tunnel --url http://localhost:3001"
```
?
2. Also, even though I can see some texts in Discord activity, none of the photos shows up as shown in the screenshot. This only happens in Discord. When I access the generated Cloudflare URL, I can see images just fine.
<img width="965" alt="image" src="https://github.com/user-attachments/assets/48cddd93-2d57-4024-b677-a83a7247ba78">

**Comment by Gregory-Hepicloud** [comment]
Same issue here no assets load
